"""empty message

Revision ID: 0462cd34e3a0
Revises: 710c47aa760a
Create Date: 2022-01-04 22:19:24.762856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0462cd34e3a0'
down_revision = '710c47aa760a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated1', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ticker_prices', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2022-01-04 11:11:25.098697+00'::timestamp with time zone"), autoincrement=False, nullable=False))
    op.drop_column('ticker_prices', 'last_updated1')
    # ### end Alembic commands ###
