"""empty message

Revision ID: 20ac425f67d9
Revises: 5820f92d184a
Create Date: 2022-01-06 23:05:51.338560

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_function import PGFunction
from sqlalchemy import text as sql_text
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '20ac425f67d9'
down_revision = '5820f92d184a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_trigger_set_timestamp = PGFunction(
        schema="public",
        signature="trigger_set_timestamp()",
        definition="returns TRIGGER AS $$\n    BEGIN\n        NEW.last_updated = NOW();\n        RETURN NEW;\n    END;\n    $$ LANGUAGE 'plpgsql'"
    )
    op.create_entity(public_trigger_set_timestamp)

    public_ticker_prices_update_last_updated = PGTrigger(
        schema="public",
        signature="update_last_updated",
        on_entity="public.ticker_prices",
        is_constraint=False,
        definition='BEFORE UPDATE ON\n        public.ticker_prices FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp()'
    )
    op.create_entity(public_ticker_prices_update_last_updated)

    public_alembic_version_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_insert)

    public_alembic_version_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_references)

    public_alembic_version_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_select)

    public_alembic_version_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_update)

    public_ticker_prices_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_insert)

    public_ticker_prices_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_references)

    public_ticker_prices_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_select)

    public_ticker_prices_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_update)

    public_alembic_version_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_delete)

    public_alembic_version_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_truncate)

    public_alembic_version_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_trigger)

    public_ticker_prices_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_truncate)

    public_ticker_prices_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_trigger)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_ticker_prices_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_trigger)

    public_ticker_prices_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_truncate)

    public_ticker_prices_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_delete)

    public_alembic_version_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_trigger)

    public_alembic_version_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_truncate)

    public_alembic_version_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_update)

    public_ticker_prices_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_select)

    public_ticker_prices_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_references)

    public_ticker_prices_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_insert)

    public_alembic_version_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_update)

    public_alembic_version_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_select)

    public_alembic_version_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_references)

    public_alembic_version_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_insert)

    public_ticker_prices_update_last_updated = PGTrigger(
        schema="public",
        signature="update_last_updated",
        on_entity="public.ticker_prices",
        is_constraint=False,
        definition='BEFORE UPDATE ON\n        public.ticker_prices FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp()'
    )
    op.drop_entity(public_ticker_prices_update_last_updated)

    public_trigger_set_timestamp = PGFunction(
        schema="public",
        signature="trigger_set_timestamp()",
        definition="returns TRIGGER AS $$\n    BEGIN\n        NEW.last_updated = NOW();\n        RETURN NEW;\n    END;\n    $$ LANGUAGE 'plpgsql'"
    )
    op.drop_entity(public_trigger_set_timestamp)

    # ### end Alembic commands ###
