"""Added a new table called watchlist and added some new columns to portfolio

Revision ID: 28a9c76a4164
Revises: eaabfc3e14a5
Create Date: 2022-02-04 17:10:51.092671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a9c76a4164'
down_revision = 'eaabfc3e14a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('watchlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('last_inserted', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['ticker_prices.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id'),
    sa.UniqueConstraint('watchlist_name'),
    sa.UniqueConstraint('watchlist_name', 'user_id', 'stock_id', name='unique_stock_in_watchlist_by_user')
    )
    op.add_column('portfolio', sa.Column('units_purchased', sa.Integer(), nullable=True))
    op.add_column('portfolio', sa.Column('units_price', sa.Numeric(), nullable=True))
    op.add_column('portfolio', sa.Column('date_purchased', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'date_purchased')
    op.drop_column('portfolio', 'units_price')
    op.drop_column('portfolio', 'units_purchased')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
