"""Generated some tables

Revision ID: 377a545758a8
Revises: 811d8b8abc32
Create Date: 2022-02-11 15:38:58.107161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377a545758a8'
down_revision = '811d8b8abc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_stories',
    sa.Column('story_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('article_updated', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('story_id')
    )
    op.create_table('ticker_prices',
    sa.Column('stock_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=15), nullable=True),
    sa.Column('sector', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=6), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('stock_name', sa.String(length=150), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('market_state', sa.String(length=20), nullable=True),
    sa.Column('quote_type', sa.String(length=10), nullable=True),
    sa.Column('market_change', sa.Float(precision=53), nullable=True),
    sa.Column('market_change_percentage', sa.Float(precision=53), nullable=True),
    sa.Column('market_high', sa.Numeric(), nullable=True),
    sa.Column('market_low', sa.Numeric(), nullable=True),
    sa.Column('market_open', sa.Numeric(), nullable=True),
    sa.Column('market_previous_close', sa.Numeric(), nullable=True),
    sa.Column('market_current_price', sa.Numeric(), nullable=True),
    sa.Column('market_volume', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('last_signed_in', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('portfolio',
    sa.Column('portfolio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('units_purchased', sa.Integer(), nullable=True),
    sa.Column('units_price', sa.Numeric(), nullable=True),
    sa.Column('date_purchased', sa.DATE(), nullable=True),
    sa.Column('last_inserted', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['ticker_prices.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('portfolio_name', 'user_id', 'stock_id', name='unique_stock_in_portfolio_by_user')
    )
    op.create_table('watchlist',
    sa.Column('watchlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('last_inserted', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['ticker_prices.stock_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id'),
    sa.UniqueConstraint('watchlist_name', 'user_id', 'stock_id', name='unique_stock_in_watchlist_by_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('portfolio')
    op.drop_table('user')
    op.drop_table('ticker_prices')
    op.drop_table('news_stories')
    # ### end Alembic commands ###
