"""revert the database back

Revision ID: 476c2a1f0b6b
Revises: d6086475abe8
Create Date: 2022-01-08 18:30:47.897807

"""
import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '476c2a1f0b6b'
down_revision = 'd6086475abe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('zip_code', sa.String(length=15), nullable=True))
    op.drop_column('ticker_prices', 'zip')
    public_alembic_version_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_trigger)

    public_alembic_version_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_truncate)

    public_alembic_version_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_trigger)

    public_ticker_prices_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_truncate)

    public_ticker_prices_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_update)

    public_ticker_prices_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_select)

    public_ticker_prices_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_references)

    public_ticker_prices_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_insert)

    public_alembic_version_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_update)

    public_alembic_version_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_select)

    public_alembic_version_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_references)

    public_alembic_version_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_insert)

    op.add_column('ticker_prices', sa.Column('zip', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('ticker_prices', 'zip_code')
    # ### end Alembic commands ###
