"""remove references to stocks

Revision ID: 49115e715485
Revises: 9419bea65b97
Create Date: 2022-01-11 19:01:56.478244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49115e715485'
down_revision = '9419bea65b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_stats',
    sa.Column('model_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('days_predicted_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('root_mean_squared_score', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('model_id', name='prediction_stats_pkey'),
    sa.UniqueConstraint('symbol', name='prediction_stats_symbol_key')
    )
    # ### end Alembic commands ###
