"""Added some triggers

Revision ID: 6a402a5a5da2
Revises: 377a545758a8
Create Date: 2022-02-11 16:12:30.746392

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '6a402a5a5da2'
down_revision = '377a545758a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_ticker_prices_update_last_updated = PGTrigger(
        schema="public",
        signature="update_last_updated",
        on_entity="public.ticker_prices",
        is_constraint=False,
        definition='BEFORE UPDATE ON\n        public.ticker_prices FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp()'
    )
    op.create_entity(public_ticker_prices_update_last_updated)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_ticker_prices_update_last_updated = PGTrigger(
        schema="public",
        signature="update_last_updated",
        on_entity="public.ticker_prices",
        is_constraint=False,
        definition='BEFORE UPDATE ON\n        public.ticker_prices FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp()'
    )
    op.drop_entity(public_ticker_prices_update_last_updated)

    # ### end Alembic commands ###
