"""give last updated a timestamp123123n12j3jkn123jk

Revision ID: 6f883994731a
Revises: 1b55ee7327c5
Create Date: 2022-01-05 14:09:15.754192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f883994731a'
down_revision = '1b55ee7327c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated_1', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ticker_prices', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ticker_prices', 'last_updated_1')
    # ### end Alembic commands ###
