"""Added some triggers and functions

Revision ID: 75627abbd454
Revises: 3c6542055135
Create Date: 2022-01-06 21:01:57.963009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75627abbd454'
down_revision = '3c6542055135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('market_volume_1', sa.BigInteger(), nullable=True))
    op.drop_column('ticker_prices', 'market_volume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('market_volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('ticker_prices', 'market_volume_1')
    # ### end Alembic commands ###
