"""Foreignkeyconstraint

Revision ID: 784b68b751e4
Revises: ba963571ecae
Create Date: 2022-02-04 15:01:10.443571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784b68b751e4'
down_revision = 'ba963571ecae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_portfolio_stock_by_user', 'portfolio', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_portfolio_stock_by_user', 'portfolio', ['portfolio_name', 'user_id', 'stock_id'])
    # ### end Alembic commands ###
