"""going back to original

Revision ID: 7fdca8a46090
Revises: e95b35a91812
Create Date: 2022-01-05 18:16:40.744143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdca8a46090'
down_revision = 'e95b35a91812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('zip_code', sa.String(length=15), nullable=True))
    op.drop_column('ticker_prices', 'zip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('zip', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_column('ticker_prices', 'zip_code')
    # ### end Alembic commands ###
