"""give last updated a timestamp

Revision ID: 841585acb535
Revises: 6f883994731a
Create Date: 2022-01-05 14:09:37.952239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '841585acb535'
down_revision = '6f883994731a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ticker_prices', 'last_updated_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated_1', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ticker_prices', 'last_updated')
    # ### end Alembic commands ###
