"""readded the currency column

Revision ID: 9fd8b6a0ef8d
Revises: 146335df4dc0
Create Date: 2022-01-04 23:13:45.647145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd8b6a0ef8d'
down_revision = '146335df4dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('currency', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_prices', 'currency')
    # ### end Alembic commands ###
