"""Removed unique constraint on portfolio/watchlist name

Revision ID: a2efea38d3a8
Revises: 28a9c76a4164
Create Date: 2022-02-04 17:36:03.774094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2efea38d3a8'
down_revision = '28a9c76a4164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('portfolio_portfolio_name_key', 'portfolio', type_='unique')
    op.drop_constraint('watchlist_watchlist_name_key', 'watchlist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('watchlist_watchlist_name_key', 'watchlist', ['watchlist_name'])
    op.create_unique_constraint('portfolio_portfolio_name_key', 'portfolio', ['portfolio_name'])
    # ### end Alembic commands ###
