"""Forgot to add column for time

Revision ID: a9245909e7fa
Revises: 050c05079002
Create Date: 2022-01-15 16:57:19.688029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9245909e7fa'
down_revision = '050c05079002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_stories', sa.Column('article_updated', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_stories', 'article_updated')
    # ### end Alembic commands ###
