"""Portfolio table is still not added

Revision ID: b2e856d9c4a1
Revises: 21232f9dae8c
Create Date: 2022-02-03 19:40:34.769042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e856d9c4a1'
down_revision = '21232f9dae8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('portfolio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('last_inserted', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('portfolio_id'),
    sa.UniqueConstraint('portfolio_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
