"""change to server on_update

Revision ID: b7898c49e789
Revises: bd2113c81aa9
Create Date: 2022-01-05 14:14:41.518332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7898c49e789'
down_revision = 'bd2113c81aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ticker_prices', 'last_updated_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated_1', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ticker_prices', 'last_updated')
    # ### end Alembic commands ###
