"""Added a foreign key regerence to stock_id in portfolio

Revision ID: c92df9890f9d
Revises: cbc3d811dc45
Create Date: 2022-02-03 20:08:07.175079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92df9890f9d'
down_revision = 'cbc3d811dc45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'portfolio', 'ticker_prices', ['stock_id'], ['stock_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    # ### end Alembic commands ###
