"""Added a foreign key regerence to user in portfolio

Revision ID: cbc3d811dc45
Revises: b2e856d9c4a1
Create Date: 2022-02-03 20:06:06.476218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc3d811dc45'
down_revision = 'b2e856d9c4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'portfolio', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    # ### end Alembic commands ###
