"""Some changes

Revision ID: ce1481a983d6
Revises: a9245909e7fa
Create Date: 2022-01-19 20:49:59.257409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1481a983d6'
down_revision = 'a9245909e7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('ticker_prices', 'stock_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('stock_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('ticker_prices', 'id')
    # ### end Alembic commands ###
