"""Added back the unique constraint

Revision ID: eaabfc3e14a5
Revises: 784b68b751e4
Create Date: 2022-02-04 15:12:01.585767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaabfc3e14a5'
down_revision = '784b68b751e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_stock_in_portfolio_by_user', 'portfolio', ['portfolio_name', 'user_id', 'stock_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_stock_in_portfolio_by_user', 'portfolio', type_='unique')
    # ### end Alembic commands ###
