"""empty message

Revision ID: 02b20ab1335f
Revises: 
Create Date: 2022-01-04 20:18:02.877346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02b20ab1335f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ticker_prices_stock_id_uindex', table_name='ticker_prices')
    op.drop_index('ticker_prices_symbol_uindex', table_name='ticker_prices')
    op.drop_table('ticker_prices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_prices',
    sa.Column('stock_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('stock_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('market_state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('quote_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('market_change', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_change_percentage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_high', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_low', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_open', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_previous_close', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_current_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('stock_id', name='ticker_prices_pk')
    )
    op.create_index('ticker_prices_symbol_uindex', 'ticker_prices', ['symbol'], unique=False)
    op.create_index('ticker_prices_stock_id_uindex', 'ticker_prices', ['stock_id'], unique=False)
    # ### end Alembic commands ###
