"""empty message

Revision ID: 0977a18b32f8
Revises: 0462cd34e3a0
Create Date: 2022-01-04 22:19:59.774601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0977a18b32f8'
down_revision = '0462cd34e3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ticker_prices', 'last_updated1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated1', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ticker_prices', 'last_updated')
    # ### end Alembic commands ###
