"""Trying again

Revision ID: 0e6ace0d4131
Revises: 476c2a1f0b6b
Create Date: 2022-01-09 11:40:53.019004

"""
from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_grant_table import PGGrantTable
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision = '0e6ace0d4131'
down_revision = '476c2a1f0b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='public', grant='INSERT', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_insert)

    public_alembic_version_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_references)

    public_alembic_version_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_select)

    public_alembic_version_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_update)

    public_ticker_prices_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_insert)

    public_ticker_prices_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_references)

    public_ticker_prices_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_select)

    public_ticker_prices_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_update)

    public_ticker_prices_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_truncate)

    public_ticker_prices_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.drop_entity(public_ticker_prices_lkwpsbsrhaerjh_trigger)

    public_alembic_version_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_delete)

    public_alembic_version_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_truncate)

    public_alembic_version_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.drop_entity(public_alembic_version_lkwpsbsrhaerjh_trigger)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_alembic_version_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_trigger)

    public_alembic_version_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_truncate)

    public_alembic_version_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='alembic_version', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_trigger = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRIGGER', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_trigger)

    public_ticker_prices_lkwpsbsrhaerjh_truncate = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='TRUNCATE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_truncate)

    public_ticker_prices_lkwpsbsrhaerjh_delete = PGGrantTable(schema='public', table='ticker_prices', columns=[], role='lkwpsbsrhaerjh', grant='DELETE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_delete)

    public_ticker_prices_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_update)

    public_ticker_prices_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_select)

    public_ticker_prices_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_references)

    public_ticker_prices_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='ticker_prices', columns=['city', 'country', 'currency', 'exchange', 'industry', 'last_updated', 'market_cap', 'market_change', 'market_change_percentage', 'market_current_price', 'market_high', 'market_low', 'market_open', 'market_previous_close', 'market_state', 'market_volume', 'quote_type', 'sector', 'stock_id', 'stock_name', 'symbol', 'zip_code'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.create_entity(public_ticker_prices_lkwpsbsrhaerjh_insert)

    public_alembic_version_lkwpsbsrhaerjh_update = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='UPDATE', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_update)

    public_alembic_version_lkwpsbsrhaerjh_select = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='SELECT', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_select)

    public_alembic_version_lkwpsbsrhaerjh_references = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='REFERENCES', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_references)

    public_alembic_version_lkwpsbsrhaerjh_insert = PGGrantTable(schema='public', table='alembic_version', columns=['version_num'], role='lkwpsbsrhaerjh', grant='INSERT', with_grant_option=True)
    op.create_entity(public_alembic_version_lkwpsbsrhaerjh_insert)

    # ### end Alembic commands ###
