"""zip_code thingy

Revision ID: 146335df4dc0
Revises: dda2d68b967f
Create Date: 2022-01-04 23:13:07.598925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146335df4dc0'
down_revision = 'dda2d68b967f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_prices', 'currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('currency', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
