"""Attempt to fix last_updated fake

Revision ID: 3c6542055135
Revises: 7fdca8a46090
Create Date: 2022-01-06 20:23:07.515552

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c6542055135'
down_revision = '7fdca8a46090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('ticker_prices', 'last_updated_1')
    # ### end Alembic commands ###
