"""change to server on_update fake

Revision ID: bd2113c81aa9
Revises: 841585acb535
Create Date: 2022-01-05 14:14:11.385904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd2113c81aa9'
down_revision = '841585acb535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated_1', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('ticker_prices', 'last_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('ticker_prices', 'last_updated_1')
    # ### end Alembic commands ###
