"""empty message

Revision ID: c632039f7baf
Revises: 02b20ab1335f
Create Date: 2022-01-04 20:56:40.897076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c632039f7baf'
down_revision = '02b20ab1335f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_prices',
    sa.Column('stock_id', sa.Integer(), server_default="nextval('ticker_prices_stock_id_seq'::regclass)", nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=True),
    sa.Column('stock_name', sa.String(length=150), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('market_state', sa.String(length=20), nullable=True),
    sa.Column('quote_type', sa.String(length=10), nullable=True),
    sa.Column('market_change', sa.Float(precision=53), nullable=True),
    sa.Column('market_change_percentage', sa.Float(precision=53), nullable=True),
    sa.Column('market_high', sa.Numeric(), nullable=True),
    sa.Column('market_low', sa.Numeric(), nullable=True),
    sa.Column('market_open', sa.Numeric(), nullable=True),
    sa.Column('market_previous_close', sa.Numeric(), nullable=True),
    sa.Column('market_current_price', sa.Numeric(), nullable=True),
    sa.Column('market_volume', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('stock_id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_prices')
    # ### end Alembic commands ###
