"""added some extra space for zip code

Revision ID: db5f2159400f
Revises: 9fd8b6a0ef8d
Create Date: 2022-01-04 23:20:54.229120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db5f2159400f'
down_revision = '9fd8b6a0ef8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker_prices', 'zip_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticker_prices', 'zip_code',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=6),
               existing_nullable=True)
    # ### end Alembic commands ###
