"""empty message

Revision ID: dda2d68b967f
Revises: 0977a18b32f8
Create Date: 2022-01-04 23:03:26.759105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda2d68b967f'
down_revision = '0977a18b32f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_prices', sa.Column('city', sa.String(length=20), nullable=True))
    op.add_column('ticker_prices', sa.Column('country', sa.String(length=30), nullable=True))
    op.add_column('ticker_prices', sa.Column('industry', sa.String(length=50), nullable=True))
    op.add_column('ticker_prices', sa.Column('zip_code', sa.String(length=6), nullable=True))
    op.add_column('ticker_prices', sa.Column('sector', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_prices', 'sector')
    op.drop_column('ticker_prices', 'zip_code')
    op.drop_column('ticker_prices', 'industry')
    op.drop_column('ticker_prices', 'country')
    op.drop_column('ticker_prices', 'city')
    # ### end Alembic commands ###
